### ISSUE TITLE
LO crashes when closing Organon (Ubuntu Mate 15.10)

### ISSUE THREAD

**Issue by Jared37** [XRoemer/Organon#88] opened 2015-12-30 04:09 UTC
It crashed after selecting the close Organon option on the menu, after closing individual .odt files after saving, after closing the "dockable organon window" and after selecting exit libreoffice from the menu. After reopening from the terminal I got this message:

(soffice:4042): GLib-GObject-WARNING **: /build/glib2.0-G_esY6/glib2.0-2.46.1/./gobject/gsignal.c:3484: signal name 'selection_changed' is invalid for instance '0x911d8d0' of type 'OOoAtkObjCompTxt'

**Comment by XRoemer** [comment] 2015-12-30 10:54
Thanks for your report. I'll have look. I've got no virtual machine of Ubuntu Mate for testing yet. I'll set it up.

Can you send me a Organon log file? Have a look at #89.

Ragards,
Xaver

**Comment by Jared37** [comment] 2015-12-30 14:27
Here's the log file for one instance of the crash
[organon_log.txt](https://github.com/XRoemer/Organon/files/74889/organon_log.txt)

**Comment by XRoemer** [comment] 2015-12-30 16:56
Ok, nothing special in the logfile. I'll install Ubuntu Mate and see 
what I can do.

What version of LO do you use?

Greets,
Xaver


Am 30.12.2015 um 15:27 schrieb Jared37:

**Comment by Jared37** [comment] 2015-12-30 19:46
Thanks for getting back so quickly. I use LO 5.0.2.2

**Comment by XRoemer** [comment] 2016-01-02 09:17
I did set up Ubuntu Mate and LO 5.0.3.2 and I couldn't reproduce your error.

I'm not sure, what might help in this case. There might be a conflict between gnome and/or OO and/or Organon threads. 

There is/was one bug on starting LO on gnome 3.18
https://bugs.archlinux.org/task/46617
(But this bug didn't let the user start LO at all.)


What I can suggest is:
- update LO to 5.0.3.2 (good idea anyway)
- start LO with sudo (I couldn't start it without)
- don't use Organon designs (Organon preferences)
- don't use the mousewheel (Organon preferences)

I hope that helps,
Xaver

**Comment by XRoemer** [comment] 2016-01-06 19:52
I closed this bug as I couldn't reproduce it and didn't get any further comments on it. If the issue still appears, reopen it.

**Closed by XRoemer** 2016-01-06 19:52 UTC
