### ISSUE TITLE
Organon fails to load

### ISSUE THREAD

**Issue by dajare** [XRoemer/Organon#31] opened 2015-04-01 09:33 UTC
I just installed Organon (from [OpenOffice extensions](http://extensions.openoffice.org/en/project/organon)) after an update to LibO Version: 4.4.2.2 Build ID: 40m0(Build:2); I'm on Ubuntu 14.04 LTS. 

The extension appears to install correctly, but when I attempt to run it ... a blank box pops up. Is there anything I can do to help debug this? I use LibO Writer constantly.

### Screenshots: 

- toolbar:

![selection_361](https://cloud.githubusercontent.com/assets/40625/6938311/60560d32-d85a-11e4-862b-63b0d065bc93.png)

- open attempt:

![selection_362](https://cloud.githubusercontent.com/assets/40625/6938304/51c49c16-d85a-11e4-8d0d-21b6081daf1b.png)

**Comment by XRoemer** [comment] 2015-04-01 13:47
Thanks for your message. I'll have a look tomorrow.





Am 01.04.2015 um 11:33 schrieb David:

**Comment by dajare** [comment] 2015-04-01 20:14
Update: I just installed this on my home machine: ancient laptop running Linux Mint 13 Xfce LTS, but the same version of LibO. Organon installed and loaded just fine.

And now I see it installed properly, I see that there should be an icon beside the "open/close" item in the Organon menu from the menu bar, but the Ubuntu install (picture above) doesn't have this. Does that suggest a path problem?

**Comment by XRoemer** [comment] 2015-04-02 04:39
I installed LO 4.4.2 on my VM in win7. Organon is working properly there.

On my laptop (kubuntu 14.04) I had issues caused by the windows management of kde. I had to disable window animation to get organon to work. But it still doesn't work properly as the Organon window can't be docked. I'm not sure if I can solve this, because I found no way to handle that from LO.

But you can try to get a log file from organon:
Find log_config.txt in the Organon extension folder. On my machine the path looks like:
/opt/libreoffice4.4/share/uno_packages/cache/uno_packages/luzlxd4g.tmp_/organon.oxt
(There might be a file error_log.txt already in this folder, as Organon logs all errors automatically.)

There are four lines in this file:
The first line is the path to the output folder of the logfiles. Initially it shows the current folder of this file. You might change it to something better reachable.
In the rest of the lines set the zero to one.
If Organon starts it should write at least one log file now.

**Comment by XRoemer** [comment] 2015-05-07 09:20
On Ubuntu I'm missing the icon as well. Nevertheless Organon works. 
It's a matter of the extension description file. I don't think, it's importand.

I close this issue as no more comments have been posted.

**Closed by XRoemer** 2015-05-07 09:20 UTC

**Comment by dajare** [comment] 2015-05-07 10:21
My LibreOffice is now at Version: 4.4.3.2 / Build ID: 40m0(Build:2). The Organon button on the toolbar still has no icon with the "open/close" menu item, but when you click it, the panel operates as expected.

When I get a bit of time, I'll see if I can work out what is happening with the icon, but meanwhile the main app is certainly working. Thanks for following this up.

**Comment by mtrun** [comment] 2017-01-21 18:52
I had this issue happen as well: there is a menu at the top that says "Organon", with a single option ("open/close"), but just a blank box comes up, with no features.

**Comment by XRoemer** [comment] 2017-01-22 07:15
Hi mtrun,
please tell me your working system and your LO version.
